name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go_version:
          - 1.13
          - 1.14
        os:
          - macos
          - ubuntu
          - windows
        goarch:
          - 386
          - amd64
        exclude:
          - os: macos
            goarch: 386

    name: test (${{ matrix.os }}/go-${{ matrix.go_version }}/${{ matrix.goarch }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      # can I run docker on windows?
      - name: test docker
        if: matrix.os != 'macos'
        run: docker run hello-world

      - uses: actions/setup-go@master
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@master

      - name: install deps
        run: |
          echo $PATH
          go mod download
          (
            cd /tmp
            env GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          )
        shell: bash
        env:
          GOARCH: ${{ matrix.goarch }}

      # - name: run-linter
      #   run: |
      #     $(go env GOPATH)/bin/golangci-lint run
      #   shell: bash
      #   env:
      #     GOPROXY: off
      #     GOFLAGS: -mod=readonly
      #     GOARCH: ${{ matrix.goarch }}

      - name: run-tests
        run: make gotest
        shell: bash
        env:
          GOARCH: ${{ matrix.goarch }}
          GOPROXY: off
