name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go_version:
          - 1.13
          - 1.14
        os:
          - macos
          - ubuntu
          - windows
        goarch:
          - 386
          - amd64
        exclude:
          - os: macos
            goarch: 386

    name: test (${{ matrix.os }}/go-${{ matrix.go_version }}/${{ matrix.goarch }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: fsouza/setup-go@add-gobin
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@master

      - run: go mod download
        env:
          GOARCH: ${{ matrix.goarch }}

      - run: make lint
        shell: bash
        env:
          GOFLAGS: -mod=readonly
          GOARCH: ${{ matrix.goarch }}

      - run: make gotest
        shell: bash
        env:
          GOARCH: ${{ matrix.goarch }}
          GOPROXY: off

      - run: make integration
        if: matrix.os != 'macos'
        shell: bash
        env:
          GOFLAGS: -mod=readonly
          GOARCH: ${{ matrix.goarch }}
